name: RNNEncoder
rnn_type: LSTM
bidirectional: True 
hidden_size: 1024 
num_layers: 2 
dropout: 0.
# embedding layer 
w_dim: 512 # word
cat_w: False
m_dim: ${.w_dim}
num_p: -1
p_dim: -1
cat_p: False
p_type: null 
w2v_file: ""
ln_input: False
skip_embed: True
