name: 'LMLossHead'
layers: []
scaling: True
alpha_l1: 0.
max_len_dec: 20
kl_warmup_steps: 0

add_dummy: ${data.add_dummy}
cate_type: ${data.cate_type} 
relation_words: ${data.relation_words}
optim_only_relation: True
